# Use a imagem baseada em Alpine com PHP 8.1 FPM
FROM php:8.1-fpm-alpine

# Arguments
ARG user=convicti
ARG uid=1000

# Atualize os pacotes do sistema operacional
RUN apk update && apk upgrade

# Instale os pacotes necessários
RUN apk add --no-cache \
    libzip-dev \
    zip \
    unzip \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    icu-dev \
    g++

# Instale as extensões PHP necessárias
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install intl \
    && docker-php-ext-install zip

# PostgreSql
# RUN apk add --no-cache openssl bash nodejs npm postgresql-dev
RUN apk add --no-cache postgresql-dev
RUN docker-php-ext-install bcmath pdo pdo_pgsql

# Instale o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# RUN echo "upload_max_filesize = 800M \n \
#     post_max_size = 800M \n \
#     memory_limit = 256M \n \
#     max_execution_time = 120" > /usr/local/etc/php/conf.d/upload.ini

#/usr/local/etc/php/conf.
RUN adduser --uid $uid --home /home/$user -s /bin/sh -D $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Crie o diretório de trabalho
WORKDIR /var/www/html

# Copie o código fonte do Laravel para o diretório de trabalho
COPY . .

# Instale as dependências do Laravel com o Composer
RUN composer install
RUN composer dump-autoload

# Defina as permissões para o diretório de trabalho
RUN chown -R www-data:www-data /var/www/html

# Defina o usuário com o qual o contêiner será executado
USER $user

# Defina o ponto de entrada para o contêiner
CMD ["php-fpm"]
